from abc import ABC, abstractmethod
from typing import List, Optional
from domain.entities.article import Article

class ArticleRepository(ABC):
    @abstractmethod
    def recuperer_tous(self, actif_seulement: bool = False) -> List[Article]: ...
    @abstractmethod
    def recuperer_par_id(self, id: int) -> Optional[Article]: ...
    @abstractmethod
    def recuperer_par_slug(self, slug: str) -> Optional[Article]: ...
    @abstractmethod
    def ajouter(self, article: Article) -> Article: ...
    @abstractmethod
    def mettre_a_jour(self, article: Article) -> Article: ...
    @abstractmethod
    def supprimer(self, id: int) -> None: ...
    @abstractmethod
    def basculer_actif(self, id: int) -> Optional[Article]: ...